// <auto-generated />
namespace Car_Price_prediction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addNEWimage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNEWimage));
        
        string IMigrationMetadata.Id
        {
            get { return "202302252159048_addNEWimage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
